// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AppWebApi.Test.Postulant
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PostulantRegisterFeature : object, Xunit.IClassFixture<PostulantRegisterFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PostulantRegister.feature"
#line hidden
        
        public PostulantRegisterFeature(PostulantRegisterFeature.FixtureData fixtureData, AppWebApi_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Postulant", "PostulantRegister", "\tAs a Developer\r\n\tI want to add new Product through API\r\n\tSo that it becomes avai" +
                    "lable for applications.\t", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add postulant")]
        [Xunit.TraitAttribute("FeatureTitle", "PostulantRegister")]
        [Xunit.TraitAttribute("Description", "Add postulant")]
        [Xunit.TraitAttribute("Category", "postulant-adding")]
        public virtual void AddPostulant()
        {
            string[] tagsOfScenario = new string[] {
                    "postulant-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add postulant", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
  testRunner.Given("The Endpoint https://localhost:5001/api/v1/postulants is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "LastName",
                            "Email",
                            "Password",
                            "MySpecialty",
                            "MyExperience",
                            "Description",
                            "NameGithub",
                            "ImgPostulant"});
                table4.AddRow(new string[] {
                            "Alex",
                            "Liza",
                            "developer-97@gmail.com",
                            "12345678",
                            "Ciencia de Datos",
                            "Junior",
                            "descripcion",
                            "gitname",
                            "xd"});
#line 9
  testRunner.When("A post request is sent", ((string)(null)), table4, "When ");
#line hidden
#line 12
  testRunner.Then("A response with Status 200 is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "LastName",
                            "Email",
                            "Password",
                            "MySpecialty",
                            "MyExperience",
                            "Description",
                            "NameGithub",
                            "ImgPostulant"});
                table5.AddRow(new string[] {
                            "1",
                            "Alex",
                            "Liza",
                            "developer-97@gmail.com",
                            "12345678",
                            "Ciencia de Datos",
                            "Junior",
                            "descripcion",
                            "gitname",
                            "xd"});
#line 13
  testRunner.And("A postulant resource is included in Response Body", ((string)(null)), table5, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid postulant")]
        [Xunit.TraitAttribute("FeatureTitle", "PostulantRegister")]
        [Xunit.TraitAttribute("Description", "Invalid postulant")]
        public virtual void InvalidPostulant()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid postulant", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 17
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
  testRunner.Given("The Endpoint https://localhost:5001/api/v1/postulants is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "LastName",
                            "Email",
                            "Password",
                            "MySpecialty",
                            "MyExperience",
                            "Description",
                            "NameGithub",
                            "ImgPostulant"});
                table6.AddRow(new string[] {
                            "",
                            "",
                            "developer-97@gmail.com",
                            "12345678",
                            "Ciencia de Datos",
                            "Junior",
                            "descripcion",
                            "gitname",
                            "xd"});
#line 19
  testRunner.When("A post request is sent", ((string)(null)), table6, "When ");
#line hidden
#line 22
     testRunner.Then("A response with Status 400 is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 23
     testRunner.And("A message is included in Response Body with value \"{\"type\":\"https://tools.ietf.or" +
                        "g/html/rfc7231#section-6.5.1\"}\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add postulant with existing email")]
        [Xunit.TraitAttribute("FeatureTitle", "PostulantRegister")]
        [Xunit.TraitAttribute("Description", "Add postulant with existing email")]
        public virtual void AddPostulantWithExistingEmail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add postulant with existing email", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 25
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "LastName",
                            "Email",
                            "Password",
                            "MySpecialty",
                            "MyExperience",
                            "Description",
                            "NameGithub",
                            "ImgPostulant"});
                table7.AddRow(new string[] {
                            "Alex",
                            "Liza",
                            "developer-97@gmail.com",
                            "12345678",
                            "CienciadeDatos",
                            "Junior",
                            "descripcion",
                            "gitname",
                            "xd"});
#line 26
  testRunner.Given("A Email is already stored", ((string)(null)), table7, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "LastName",
                            "Email",
                            "Password",
                            "MySpecialty",
                            "MyExperience",
                            "Description",
                            "NameGithub",
                            "ImgPostulant"});
                table8.AddRow(new string[] {
                            "Diego",
                            "Perez",
                            "developer-97@gmail.com",
                            "1234abcd",
                            "Ciencia de Datos",
                            "Senior",
                            "descripcion",
                            "gitname",
                            "xd"});
#line 29
  testRunner.When("A post request is sent", ((string)(null)), table8, "When ");
#line hidden
#line 32
  testRunner.Then("A response with Status 400 is received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
  testRunner.And("A message is included in Response Body with value \"Email is already exist.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PostulantRegisterFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PostulantRegisterFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
